### ISSUE TITLE
Is there a quick way to download raw images?

### ISSUE THREAD

**Issue by PhoebusSi** [allenai/mmc4#7]
Downloading images directly from various websites is too slow. Do you have any packaged image files available?

**Comment by jmhessel** [comment]
Hi @PhoebusSi ! At the moment, for legal reasons we cannot provide bulk access to raw image files. However, 1) we are looking into options because we understand this makes using the dataset more difficult; and 2) we are planning to provide the multi-threaded downloading script that we used to gather many images in a short time.
